name: CI

on:
    push:
        branches: ["dev"]
    pull_request:
        branches: ["dev"]

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm install -g pnpm
            - run: pnpm i
            - run: pnpm build
